workflows:
  ios-release:
    name: iOS production release
    max_build_duration: 45
    integrations:
      app_store_connect: DevFin API Key
    environment:
      ios_signing:
        provisioning_profiles:
          - DevFin Profile
        certificates:
          - DevFin Apple Cert
      groups:
        - code-signing
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace" # <-- Put your encrypted Certificate Private Key here
        # Environment variable values provided when triggering build with Codemagic API. Alternatively add the required values below.
        APP_STORE_APP_ID: 6476280284 # <-- Put the app id number here. This is found in App Store Connect > App > General > App Information
        XCODE_CONFIG: Release-production # <-- Put the Xcode configuration here. This is found in Xcode > Project > Info > Configurations
        XCODE_SCHEME: production # <-- Put the Xcode scheme here. This is found in Xcode > Product > Scheme > Edit Scheme
        BUNDLE_ID: com.negandev.devfin # <-- Put the bundle id here. This is found in Xcode > Runner [Target] > General > Identity > Bundle Identifier
        ENTRY_POINT: lib/main_production.dart
      flutter: 3.16.0
      xcode: 15.1 # <-- set to specific version e.g. 14.3, 15.0 to avoid unexpected updates.
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
    scripts:
      - name: Get Flutter Packages
        script: |
          flutter packages pub get
      - name: Pod install
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
      - name: Add certs to keychain
        script: |
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Flutter build ipa and automatic versioning
        script: |
          echo "XCODE_SCHEME: $XCODE_SCHEME"
          echo "ENTRY_POINT: $ENTRY_POINT"
          flutter build ipa --release --flavor="$XCODE_SCHEME" -t "$ENTRY_POINT" \
          --build-name=1.0.0 \
          --build-number=$(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_ID") + 1)) \
          --export-options-plist=/Users/builder/export_options.plist \

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - huykgit98@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect: # checkout https://docs.codemagic.io/yaml-publishing/app-store-connect/ for more information
        auth: integration
        submit_to_testflight: true # Optional boolean, defaults to false. Whether or not to submit the uploaded build to TestFlight beta review. Required for distributing to beta groups. Note: This action is performed during post-processing.
        expire_build_submitted_for_review: true
