name: devfin
description: Devfin - Real-time financial news, markets data and investing analysis
version: 1.0.0+1
repository: https://github.com/huykgit98/devfin
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.3.0
  connectivity_plus: ^5.0.2
  easy_debounce: ^2.0.3
  equatable: ^2.0.5
  firebase_core: ^2.24.2
  firebase_storage: ^11.5.5

  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  formz: ^0.6.1
  get_it: ^7.6.4
  go_router: ^12.1.3
  intl: ^0.18.0
  isar: ^3.1.0+1
  lazy_load_indexed_stack: ^1.0.1


dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.2
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
