name: devfin
description: Devfin - Real-time financial news, markets data and investing analysis
version: 1.0.0+1
repository: https://github.com/huykgit98/devfin
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  go_router: ^13.0.1
  floating_draggable_widget: ^2.1.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  fl_chart: ^0.65.0
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.2
  flutter_native_splash: ^2.3.9
  scrollable_positioned_list: ^0.3.8
  scroll_to_index: ^3.0.1
  carousel_slider: ^4.2.1
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.4.9
  google_fonts: ^6.1.0
  drag_and_drop_lists: ^0.3.3
  firebase_core: ^2.24.2
  flutter_launcher_icons: ^0.13.1
  animated_bottom_navigation_bar: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^3.0.1
  bloc_test: ^9.1.4
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  generate: true

flutter_gen:
  output: lib/app/config/gen/

flutter_native_splash:
  color: '#ffffff'
  image: assets/icons/app_icon_transparent_bg.png
  color_dark: '#000000'
  image_dark: assets/icons/app_icon_dark_theme_transparent_bg.png
