name: crypto_repository
description: Crypto repository
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  coincap_api:
    path: ../coincap_api

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.21.4