name: coincap_data_source
description: CoinCap datasource
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  models:
    path: ../models

  flutter:
    sdk: flutter
  web_socket_channel: ^2.4.0
  http: ^1.2.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
